### ISSUE TITLE
Demo site is down

### ISSUE THREAD

**Issue by hung-native** [1inch/embedded-widget#2]
After I connect to my MetaMask, it shows the errors below. Is it some policy changes on browser that breaks this?

![image](https://user-images.githubusercontent.com/124560975/217168409-c5e659ae-b5bf-4922-afb1-2a4d678e6b6d.png)

![image](https://user-images.githubusercontent.com/124560975/217168439-7443283e-637c-44c3-9277-0d2e13956f33.png)

**Comment by hananbeer** [comment]
demo is not down, 1inch.io don't have the proper Content Security Policy anymore.

**Comment by smelnikov** [comment]
I have the same problem, but sometimes the widget loads.

@shoom3301 maybe the author of the code can help us?

**Comment by shoom3301** [comment]
Hi!
Sorry, I can't help with that.
@artall64 probably can

**Comment by artall64** [comment]
@smelnikov at the moment CSP rules is enforced, so embedded mode doesn't work. 
I'll get back to you shortly with information on the further embedded mode support.
cc @MitkoTschimev

**Comment by defifund** [comment]
Hi, @artall64 Are there other available integration models? Much appreciated.

**Comment by artall64** [comment]
@defifund at the moment integration is possible via API https://portal.1inch.dev. Other option is Iframe, but for such kind of integration you would need to reach 1inch team to white list your domain

**Comment by defifund** [comment]
extremely grateful
